### ISSUE TITLE
warning in st2

### ISSUE THREAD

**Issue by chloelulu** [biota/sourcetracker2#100]
Hi, 
When I type in sourcetracker2 --version or run the sourcetracker2, it always gives me this error message. 
/.conda/envs/st2/lib/python3.5/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
sourcetracker2, version 2.0.1
May I know the reason and how to cancel this error?

Thanks.

**Comment by johnchase** [comment]
For anyone interested in this warning it is due to a chagne in numpy 1.14.0 it can be removed by downgrading to 1.13.0 or just ignoring it

https://github.com/h5py/h5py/issues/974
