### ISSUE TITLE
OTUs contributing

### ISSUE THREAD

**Issue by srithegreat** [biota/sourcetracker2#104]
I wanted to know if there is a way to know which taxa contribute to each of the fractions of sources in the results?

**Comment by johnchase** [comment]
@srithegreat If you pass the flag `--per_sink_feature_assignments` the output will include a table for each of the sinks where there will be a count for the source of origin of each feature. Does this get you what you need?

**Comment by srithegreat** [comment]
Thanks, but I am interested to know which OTUs correspond to the counts.

**Comment by johnchase** [comment]
Sorry, if that was unclear. The features to which I was referring will be OTUs if you are running sourcetracker with a table of OTUs.

**Comment by johnchase** [comment]
Closing for now, however, comments may still be posted
