### ISSUE TITLE
Mapping file or biom table passed contain no `source` samples.

### ISSUE THREAD

**Issue by heatherdeel** [biota/sourcetracker2#107]
Hello, 
I've been trying to use sourcetracker and keep getting the following error: "Mapping file or biom table passed contain no `source` samples.". My mapping file definitely contains a "SourceSink" column with each source and sink labeled, so I am wondering if this issue has something to do with my biom table.
 
My biom table was imported to QIIME2 as a QIIME2 artifact, filtered, and exported as a biom table, so I am not sure if this is a QIIME2 issue when exporting my biom table or if it is a sourcetracker issue with my mapping file. 

Does anyone have some input on this?

Thank you!
Heather Deel

**Comment by johnchase** [comment]
Hi Heather, are you able to provide a small sample of your data and the command that you are running?

**Comment by heatherdeel** [comment]
Hello, 
Thank you for such a quick reply!
Here, I have attached the mapping file I've been using in the command, and here is the command I ran:

sourcetracker2 gibbs -i table_sourcetracker.biom -m maps/bone_skin_soil_map_st_filtered.txt -o prop_source_in_sinks/

I've also attached the first few lines of data in my biom table. 

Thanks so much for your help!

[data_sample.txt](https://github.com/biota/sourcetracker2/files/2125196/data_sample.txt)

[bone_skin_soil_map_st_filtered.txt](https://github.com/biota/sourcetracker2/files/2125172/bone_skin_soil_map_st_filtered.txt)

**Comment by johnchase** [comment]
Great, glad that helped! If it turns out to not be the case feel free to reopen
