### ISSUE TITLE
Full output

### ISSUE THREAD

**Issue by lkursell** [biota/sourcetracker2#13]
Include the full output of the average count of each bug from each source in the sink sample

**Comment by wdwvt1** [comment]
The QIIME forum recently had a [request](https://groups.google.com/forum/#!topic/qiime-forum/f0sEYp-JMlc) by a user for full output. Evidence that we need to find a way to get this working

**Comment by lkursell** [comment]
@wdwvt1 Yes, I think a full out put will be necessary. At the moment we can't track which OTUs are the most important for providing contribution density to sinks. I think the best way to return this would be a dataframe of `features X sinks`. If I remember correctly, the SourceTracker1 returned the full output, but it didn't specify the observation ID - they got renumbered to `V1, V2,..., Vn`. Therefore lets make sure that the observation IDs get reported.

**Comment by wdwvt1** [comment]
Resolved in PR #51.
