### ISSUE TITLE
How to install qiime sourcetracker2 gibbs

### ISSUE THREAD

**Issue by srosales712** [biota/sourcetracker2#131]
Hi - I'm running qiime2-2020.6 and I was wondering if the qiime sourcetracker2 gibbs plugging is available for this version of qiime2. I looked over a tutorial (pasted below) and through the qiime2 resources, but I don't see any methods on how to install sourcetracker2 gibbs within the qiime2 environment. Any suggestions?

Thanks,
Stephanie

https://nbviewer.jupyter.org/github/cameronmartino/sourcetracker2/blob/q2plugin/ipynb/Sourcetracking-using-QIIME2.ipynb

**Comment by johnchase** [comment]
Hi @srosales712 The installation instructions are on the main page of this repository. You can find them here: https://github.com/biota/sourcetracker2#installation

**Comment by zhangbenbenchina** [comment]
> 您好 - 我正在运行 qiime2-2020.6，我想知道下面 qiime sourcetracker2 gibbs 插件是否适用于 qiime2 的版本。我查看了教程（粘贴在）并浏览了 qiime2 资源，但我没有在 qiime2 看到任何相关如何操作环境中安装sourcetracker2 gibbs的方法。有什么建议么？
> 
> 谢谢， 斯蒂芬妮
> 
> https://nbviewer.jupyter.org/github/cameronmartino/sourcetracker2/blob/q2plugin/ipynb/Sourcetracking-using-QIIME2.ipynb

Hello Professor, could you please provide me with a tutorial on how to install the sourcetarcker plug-in in qiime2?
