### ISSUE TITLE
Installation issue -- parso requires Python >=3.6

### ISSUE THREAD

**Issue by TayteCampbell** [biota/sourcetracker2#134]
When I try and install sourcetracker2 using the regular 'pip install sourcetracker' command I get the error message:

parso requires Python '>=3.6' but the running Python is 3.5.6
You are using pip version 10.0.1, however version 20.3.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.

This results in sourcetracker2 not being installed.

I have tried updating the pip version within this conda environment using 'pip install --upgrade pip' and then trying to reinstall sourcetracker2 with 'pip install sourcetracker'

This results in the installation of sourcetracker2 but when I try to run 'sourcetracker2 gibbs --help' I get the following error:

    node_map: Dict[str, type] = {}
            ^
SyntaxError: invalid syntax

**Comment by TayteCampbell** [comment]
I've found that I can get it to work if I just do the following:

conda create -n st2
conda activate st2
pip install sourcetracker

Is this alteration in the installation going to cause issues?

**Comment by gaoyu19920914** [comment]
As mentioned in the [official page of the project parso](https://pypi.org/project/parso/), the 0.7.1 version is the latest version supporting python 3.5:
> 0.7.1 (2020-07-24)
>
>    Fixed a couple of smaller bugs (mostly syntax error detection in Grammar.iter_errors)
>
> *This is going to be the last release that supports Python 2.7, 3.4 and 3.5.*

I typed `pip install parso==0.7.1` before running `pip install sourcetracker` in the conda environment "st2".
Here is the notification I got:
> Successfully built sourcetracker
> mkl-random 1.0.1 requires cython, which is not installed.

and I then typed `pip install cython`, it seems to be resolved:
> Successfully installed cython-0.29.21.

**Comment by KMKemp** [comment]
I just successfully installed by placing `python=3.5` with `python=3.6`. Seems to be working fine.

```
conda create -n st2 -c biocore python=3.5 numpy scipy scikit-bio biom-format h5py hdf5 seaborn
conda activate st2
pip install sourcetracker
```

**Comment by TayteCampbell** [comment]
> As mentioned in the [official page of the project parso](https://pypi.org/project/parso/), the 0.7.1 version is the latest version supporting python 3.5:
> 
> > 0.7.1 (2020-07-24)
> > Fixed a couple of smaller bugs (mostly syntax error detection in Grammar.iter_errors)
> > _This is going to be the last release that supports Python 2.7, 3.4 and 3.5._
> 
> I typed `pip install parso==0.7.1` before running `pip install sourcetracker` in the conda environment "st2".
> Here is the notification I got:
> 
> > Successfully built sourcetracker
> > mkl-random 1.0.1 requires cython, which is not installed.
> 
> and I then typed `pip install cython`, it seems to be resolved:
> 
> > Successfully installed cython-0.29.21.

Thank you, this installation seems to have worked
