### ISSUE TITLE
ipcluster can remain open in some circumstances

### ISSUE THREAD

**Issue by gregcaporaso** [biota/sourcetracker2#20]
_From @wdwvt1 on February 27, 2016 7:40_

If a user deletes the output folder that has been created before all the jobs launched by `IPcluster` have finished, the cluster will fail to shut itself down. This could cause serious resource leaks. 

_Copied from original issue: biota/sourcetracker2_internal#23_

**Comment by wdwvt1** [comment]
@gregcaporaso noted that we need to close the cluster if `gibbs` or `gibbs_loo` fail.

**Comment by wdwvt1** [comment]
@wasade mentioned using the `atexit` functionality [here](https://docs.python.org/3/library/atexit.html)

**Comment by wasade** [comment]
It might be worth replacing ipcluster with joblib, although I don't know how coupled the codebase is at this time. Joblib is super simple, performant, what scikit-learn uses, and can use a ipython cluster backend anyway if it is necessary to span multiple nodes

**Comment by johnchase** [comment]
@wdwvt1 this should be fixed by #117
