### ISSUE TITLE
Visualization of mixing probabilities

### ISSUE THREAD

**Issue by gregcaporaso** [biota/sourcetracker2#25]
_From @lkursell on January 29, 2016 22:23_

Want a quick function, or --flag, to pass so that the results can be visualized. Bar chart is likely most helpful. Might have some upper limits on number of sinks/sources for which the figures make sense.

_Copied from original issue: biota/sourcetracker2_internal#8_

**Comment by gregcaporaso** [comment]
_From @wdwvt1 on January 30, 2016 0:58_

discussed with @lkursell - maybe radar charts would be a good thing to use here
![image](https://cloud.githubusercontent.com/assets/1048569/12692272/9333e0e2-c6a9-11e5-8ac9-23afe499ad2f.png)

**Comment by wdwvt1** [comment]
Our default heatmap output gives a less pretty but just as functional version of this now. Sufficient for most use cases I think.
