### ISSUE TITLE
migrate functionality that is in sourcetracker2_internal but not sourcetracker2

### ISSUE THREAD

**Issue by gregcaporaso** [biota/sourcetracker2#29]
@wdwvt1, @lkursell mentioned that you have some code that is in sourcetracker2_internal which is not in sourcetracker2. Can you issue a pull request that moves that code to sourcetracker2? We'll then be getting rid of the sourcetracker2_internal repository (email to follow shortly on the new strategy for internal development).

**Comment by lkursell** [comment]
This is in reference to the simulation code

**Comment by gregcaporaso** [comment]
Just wanted to check whether there was any progress on this.

**Comment by lkursell** [comment]
@wdwvt1 not that I know of. I don't think it should hold up the release though, it was very very early code

**Comment by gregcaporaso** [comment]
I agree about the release - just was skimming through the open issues while waiting on tests.
