### ISSUE TITLE
initial (2.0.1) alpha release

### ISSUE THREAD

**Issue by gregcaporaso** [biota/sourcetracker2#30]
Address comments in #38 before building this release (that was accidentally merged before the comments were addressed, but the comments were minor).

**Comment by lkursell** [comment]
@gregcaporaso I just merged @wdwvt1's latest pull request. So we are all good for you to add in your changes for sink/source column calls and issue the alpha release.

**Comment by gregcaporaso** [comment]
I'm on it this weekend - thanks!
