### ISSUE TITLE
delay parameter

### ISSUE THREAD

**Issue by wdwvt1** [biota/sourcetracker2#33]
if the `delay` parameter in the `gibbs_sampler` function is set to `1` the function will never take draws (x-y mod 1 always = 0). 

this is a legacy from the original sourcetracker code. we need to establish if there is any reason that a delay of 1 is unacceptable and rewrite the checker if not.

**Comment by wdwvt1** [comment]
got bitten by this bug this morning - need to get this figured out.

**Comment by lkursell** [comment]
It sounds reasonable that someone would want to collect every draw after a certain burn in period, so we should allow it
