### ISSUE TITLE
_gibbs fails on dataframes with floats

### ISSUE THREAD

**Issue by lkursell** [biota/sourcetracker2#41]
`_gibbs` fails with:
`
IndexError: index 6283 is out of bounds for axis 0 with size 6283
`
When the are floats in the `sink_df`. The error occurs when trying to create the `order` to walk through the sequences.

Probably want to add a check so that a less cryptic error message is given to the user.

**Comment by wdwvt1** [comment]
Can you post the dataset + command that causes this. I thought I had every error where an index error occurs isolated, but definitely need to see what slipped through.

**Comment by wdwvt1** [comment]
this can be resolved by changing line 529 in `sourcetracker2/sourcetracker.py` to be `sink_sum = np.int(sink.sum())`. alternatively we can floor or ceiling this value, but we just need to ensure its not non-integer.

**Comment by lkursell** [comment]
Should we make the user address their int problem? or just call floor and add a note saying that is what we do?

**Comment by wdwvt1** [comment]
This is now resolved in PR #51 and noted in the readme.md.
