### ISSUE TITLE
Unexpected behavior with null values in api call

### ISSUE THREAD

**Issue by johnchase** [biota/sourcetracker2#46]
The private api call `_gibbs` has unexpected behavior when null values are present in the source table.

For example

```python 
sink = pd.DataFrame([[1, 2], [1, 0]], index=['x', 'y'])
source = pd.DataFrame([[1, 2], [np.nan, np.nan]], index=['v', 'z'])

mix, std = _gibbs(source, sink)
mix

	v	z	Unknown
x	1.0	0.0	0.0
y	1.0	0.0	0.0
```
The simplest and probably easiest solution is to return an error if null values are present in the source or sink tables.

**Comment by wdwvt1** [comment]
Now fixing this as part of my `pd_internals` branch.
