### ISSUE TITLE
Adding functionality to SourceTracker 2

### ISSUE THREAD

**Issue by drscottkelley** [biota/sourcetracker2#52]
One of the best things I thought Dan changed in ST1 later version is that it could tell you which *specific* OTUs were specific for a particular environment. This would be very useful indeed if we could add this functionality or add it to the instructions if easy to do.

**Comment by drscottkelley** [comment]
I found the functionality in Sourcetracker 1: It was deposited in a subfolder called full_results:
From Dan Knight: "The newest version of SourceTracker (0.9.7) by default outputs this information to a subfolder called full_results. This folder contains one tab-delimited table for each source environment (including Unknown). In each table the rows are the samples, the columns are the OTUs/taxa/microbes, and the entries are the predicted relative contribution to that sample of that microbe from the given source environment."

**Comment by wdwvt1** [comment]
@drscottkelley - absolutely. We have implemented this in a pull request (pr #51) and are testing/preparing to merge now.

**Comment by wdwvt1** [comment]
@drscottkelley - this feature is now in the main branch of ST2. Look at the option `--per_sink_feature_assignments`.
