### ISSUE TITLE
install fails on linux 64

### ISSUE THREAD

**Issue by wdwvt1** [biota/sourcetracker2#63]
A QIIME forum user reported an error installing because conda couldn't find `scikitbio=0.4.3`. Conda auto-suggested `scikit-bio` instead, which I think should work, but need to investigate this failure. 

@gregcaporaso - is this a problem with our install documentation or does that user need to just add e.g. the `bioconda` channel?

**Comment by wdwvt1** [comment]
I told the user to try explicitly using the `bioconda` and that worked. Will update `README.md` to reflect .

**Comment by gregcaporaso** [comment]
You should update it to use the ``biocore`` channel, not ``bioconda``. We have control over the version on biocore, but not on bioconda.
