### ISSUE TITLE
Per_sink_feature_assignments not found

### ISSUE THREAD

**Issue by dsouzamel** [biota/sourcetracker2#85]
I re-installed sourcetracker2 to use the new, added feature --per_sink_feature_assignments and get the following error:

Error: no such option: --per_sink_feature_assignments

This feature was added: https://github.com/biota/sourcetracker2/issues/52#issuecomment-234599669

**Comment by wdwvt1** [comment]
hi @dsouzamel -  how did you install st2? the code currently has that parameter [(at this line)](https://github.com/biota/sourcetracker2/blob/master/sourcetracker/_cli/gibbs.py#L109), and the latest build has tests of that feature suggesting its working. My best guess is that you've somehow installed an older branch.

**Comment by dsouzamel** [comment]
Hey - I used the pip install instructions in conda. I do everything in
terminal as per installation instructions (i.e. pip install sourcetracker).
How do I uninstall and re-install sourcetracker from a newer branch?
Thanks.

**Comment by wdwvt1** [comment]
Ahh - pip still must not be updated to the latest version. To resolve that, you can give pip a specific link to download from. So do:

```bash
source activate whatever_your_st2_env_is
pip uninstall sourcetracker2
pip install https://github.com/biota/sourcetracker2/archive/master.zip
# if that fails, try http://github.com/biota/sourcetracker2/archive/master.zip
```

@gregcaporaso - can you update pip with the latest master branch?

**Comment by gregcaporaso** [comment]
> @gregcaporaso - can you update pip with the latest master branch?

That's not possible to do - we need to have a release and then upload it to pypi for pip to find it. Should we be thinking about a release?  I could help the week of 10/17 (after I get back from the Iceland workshop).

**Comment by wdwvt1** [comment]
@gregcaporaso - ahh, I definitely misunderstood how pip/pypi works, thanks for the explanation. I'll come up with a plan for a set of milestones and then we can chat offline.

**Comment by dsouzamel** [comment]
Hey, so I tried that and now I get a new message (see below) and the progam does nothing anymore:

/Users/labadmin/anaconda3/envs/st2/lib/python3.5/site-packages/IPython/html.py:14: ShimWarning: The `IPython.html` package has been deprecated. You should import from `notebook` instead. `IPython.html.widgets` has moved to `ipywidgets`.
  "`IPython.html.widgets` has moved to `ipywidgets`.", ShimWarning)

**Comment by wdwvt1** [comment]
That is just an expected warning from Ipython - it's not related to ST2 - and doesn't indicate any problems. 

When you say "does nothing anymore" what do you mean?

If you activate your st2 environment, then issue the command `sourcetracker2 gibbs --help`, what do you get as the output?

**Comment by dsouzamel** [comment]
So with sourcetracker2 gibbs --help I get the entire help function write out.

When I run it with real samples (i.e. with a mapfile and biom file) I get no output besides output folder creation. That folder sits empty for 20 mins (before which I kill the job).

**Comment by wdwvt1** [comment]
That strongly suggests you are killing the job before its finished. You need to wait longer. To verify this is the case. Try using your data with much less computationally demanding parameters. For instance, try:

`sourcetracker2 gibbs -i /whatever/your/table/fp/is.biom -m /whatever/your/map/fp/is.txt -o /out/path/ --restarts 1 --draws_per_restart 1 --burnin 15 --delay 1 --source_rarefaction_depth 1000 --sink_rarefaction_depth 1000`

These are fast running parameters which should finish in 20 minutes given the following things. 
1.  You have a reasonably sized data set, e.g. less than 500 sink samples. 
2.  You have available RAM and are not swapping to hard disk. If you don't know what this means, look it up - its one of the most common causes of long running times. 
3.  You have free processors on your computer.

**Comment by adityabandla** [comment]
Can the installation instructions be modified please to reflect this? The package available through pip seems to have multiple issues

**Comment by johnchase** [comment]
Hi @adityabandla I opened a new issue #123. I am closing this issue as it is outdated.

If you are interested in updating the installation instructions and issuing a pull request it would be much appreciated!
