### ISSUE TITLE
Possibly look into the Python builtin `multiprocessing` for parallelization?

### ISSUE THREAD

**Issue by jakereps** [biota/sourcetracker2#92]
Ran into a dependency issue on a plane recently, where I didn't have `ipyparallel` installed (development environment), so couldn't utilize parallelization. Barring any hard dependencies with `ipyparallel` it seems it'd make sense to swap for native python parallelization through the [`multiprocessing`](https://docs.python.org/3/library/multiprocessing.html) package.

I could kick up a benchmark to see if there are any gains or losses between the two.

**Comment by johnchase** [comment]
@jakereps Have you looked into this? No worries if not, but I might take a look at it

**Comment by nick-youngblut** [comment]
`ipyparallel` is also a pain when running multiple instances of `sourcetracker2` in parallel (eg., for testing the effects of differing parameters in a systematic way). Each separate run of `sourcetracker2` runs `subprocess.Popen('ipcluster start -n %s --quiet' % jobs, shell=True)`, so the controller is started more than once. These causes `sourcetracker2` to error and die. Instead, I have to use only 1 job per `sourcetracker2` run, which results in runs taking >80 hours in some instances.
