### ISSUE TITLE
Hangup signal lost

### ISSUE THREAD

**Issue by gfragiadakis** [biota/sourcetracker2#98]
When running sourcetracker2 I get this warning message: 

/home/gabif/miniconda3/envs/st2/lib/python3.5/site-packages/ipyparallel/client/client.py:458: RuntimeWarning:
            Controller appears to be listening on localhost, but not on this machine.
            If this is true, you should specify Client(...,sshserver='you@mac-nugget')
            or instruct your controller to listen on an external IP.
  RuntimeWarning)

Everything runs fine, the job completes and the files get written, but this connection doesn't get hung up (and I need to ctrl-C it once checking the output is there).

**Comment by bioinformatist** [comment]
I also meet this problem when use latest sourcetracker2.
I try `ipcontroller --ip=*` but it does not works too.
This is content of my `/etc/hosts`:

```pre
127.0.0.1       localhost
127.0.1.1       Metabiolab-server
::1     localhost ip6-localhost ip6-loopback
ff02::1 ip6-allnodes
ff02::2 ip6-allrouters
```

Can you help us? @johnchase 
Thank you!

**Comment by johnchase** [comment]
Unfortunately I don't have a good solution for this. This is an issue with ipyparallel, and I don't know of a good workaround. The issue in is posted in ipyparallel https://github.com/ipython/ipyparallel/issues/316 

We have discussed moving away from ipyparallel as a dependency and I believe this is how we should move forward
https://github.com/biota/sourcetracker2/issues/92
